// Mocks generated by Mockito 5.4.6 from annotations
// in crypto_app/test/core/repositories/market_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:ft_foundation/network/crypto_http_client.dart' as _i3;
import 'package:ft_foundation/network/http_request_definition.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CryptoHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCryptoHttpClient extends _i1.Mock implements _i3.CryptoHttpClient {
  MockCryptoHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<T> execute<T>(_i4.RequestDefinition<T>? requestDefinition) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [requestDefinition]),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#execute, [requestDefinition]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#execute, [requestDefinition]),
                ),
          )
          as _i2.Future<T>);
}
